static char const* const _introspection_block_xml = 
"<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\" \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n"
"<node>\n"
"    <interface name=\"org.freedesktop.DBus.Introspectable\">\n"
"        <method name=\"Introspect\">\n"
"            <arg name=\"data\" direction=\"out\" type=\"s\" />\n"
"        </method>\n"
"    </interface>\n"
"    <interface name=\"org.freedesktop.DBus.Properties\">\n"
"        <method name=\"Get\">\n"
"            <arg direction=\"in\" type=\"s\" />\n"
"            <arg direction=\"in\" type=\"s\" />\n"
"            <arg direction=\"out\" type=\"v\" />\n"
"        </method>\n"
"        <method name=\"Set\">\n"
"            <arg direction=\"in\" type=\"s\" />\n"
"            <arg direction=\"in\" type=\"s\" />\n"
"            <arg direction=\"in\" type=\"v\" />\n"
"        </method>\n"
"        <method name=\"GetAll\">\n"
"            <arg direction=\"in\" type=\"s\" />\n"
"            <arg direction=\"out\" type=\"a{sv}\" />\n"
"        </method>\n"
"        <signal name=\"PropertiesChanged\">\n"
"            <arg type=\"s\" />\n"
"            <arg type=\"a{sv}\" />\n"
"            <arg type=\"as\" />\n"
"        </signal>\n"
"    </interface>\n"
"    <interface name=\"org.sarcharsoftware.chaind.block\">\n"
"        <method name=\"Serialize\">\n"
"        </method>\n"
"    </interface>\n"
"</node>\n"
;
